### ISSUE TITLE
WINNING THE FOSSIL FUEL END GAME

### ISSUE THREAD

**Issue by drnw** [tilix/tilix.github.io#14]
Embedding from Slides.com does not work on several levels. This post needs to be converted into a proper blog.

**Comment by drnw** [comment]
I've deleted said post from the master branch. That leaves 5 posts. Is that enough for launch?

**Comment by paulohagan** [comment]
5 Posts for Launch will be enough.

**Comment by drnw** [comment]
Yes, the Sales Lion agrees too:

**The Initial Content Burst**
After you have brainstormed all your consumer questions and assigned your dates and authors, it’s a great idea, when possible, to launch a strong foundation of content at the beginning of your blog. In some cases, because of the lack of manpower, you may only be able to post one single article at first, which is fine. But if you have multiple contributors, I’d recommend 5-15 initial posts out of the gate. Notwithstanding, do not delay the launch of your company’s blog just to stockpile large amounts of content for the launch. Get it out there!
