### ISSUE TITLE
Images not filling viewport

### ISSUE THREAD

**Issue by drnw** [tilix/tilix.github.io#3]
With narrow width devices or windows the header and footer images are not filling the view port. In the screen shot below you can see the margins left and right around the home page hero image.

![screen shot 2017-07-28 at 09 10 39](https://user-images.githubusercontent.com/24733582/28708637-d56381c4-7374-11e7-88c1-fb24915eb125.png)

@milomedia can you advise on the required CSS change?

**Comment by milomedia** [comment]
In the bootstrap css the container class that wraps the content has padding left and right of 15px under 768px so this is causing the problem.

It is only on the slider under header tag so you can create a media for max width 768 and set a negative margin.

Code as follows:

@media (min-width: 768px) {
  header {
  margin-left: -15px;
 margin-right: -15px; }
}
