### ISSUE TITLE
Active Menu Item

### ISSUE THREAD

**Issue by drnw** [tilix/tilix.github.io#4]
The main menu does not highlight the active item like it does in the single page site at www.tilix.uk

**Comment by drnw** [comment]
Pull request #6 provides a solution

**Comment by milomedia** [comment]
Is this working ok now ?

**Comment by drnw** [comment]
I'm happy with my solution. With a positive peer review, we can close the issue.

**Comment by milomedia** [comment]
Yes reviewed and working the same as homepage anchored links so all good.
